version: '2'
services:
  nis:
    image: "ryuyangu/nem"
    ports:
    - "7890:7890"
    volumes:
    - nem:/var/run/nem
    environment:
    - "NEM_NETWORK=testnet"
    - "NIS_ADDITIONAL_LOCAL_IPS=192.168.1.4"
    - "NEM_MAX_THREADS=64"
    - "NIS_SHOULD_AUTO_HARVEST_ON_BOOT=false"
    - "NEM_JAVA_MEMORY=1024"
    restart: on-failure

volumes:
  nem:
